# Generated by Django 6.0.2 on 2026-03-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, verbose_name='Никнейм'),
        ),
    ]
